title: Your awesome title
email: your-email@example.com
description: ""

port: 4444
url: "uplersgitdev.github.io"
baseurl: "/html"

# url: ""
# baseurl: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
